[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=2629743"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=2629743"

[[headers]]
  for = "*.eot" # font files
  [headers.values]
    Cache-Control = "public, max-age=31556926"
[[headers]]
  for = "*.woff" # font files
  [headers.values]
    Cache-Control = "public, max-age=31556926"
[[headers]]
  for = "*.woff2" # font files
  [headers.values]
    Cache-Control = "public, max-age=31556926"
[[headers]]
  for = "*.ttf" # font files
  [headers.values]
    Cache-Control = "public, max-age=31556926"


[context.production.environment]
  API_GATEWAY_URL = "https://api.conecto.ca"
  API_GATEWAY_REGION = "us-east-1"

  GTM_ID = "GTM-W568VCF"

  GOOGLEMAP_API_KEY = "AIzaSyD81hNpyP2mL0vgZ1YYKGhpJ-b3ILrfB1A"

[context.branch-deploy.environment]
  API_GATEWAY_URL = "https://dev-api.conecto.ca"
  API_GATEWAY_REGION = "us-east-1"

  GTM_ID = "GTM-MTXQ6PN"

  GOOGLEMAP_API_KEY = "AIzaSyCbG_fT2IbSNOEcHXUo9MYY_6hvZKIQ17E"

[context.local_dev.environment]
  API_GATEWAY_URL = "https://dev-api.conecto.ca"
  API_GATEWAY_REGION = "us-east-1"

  GTM_ID = "GTM-MTXQ6PN"

  GOOGLEMAP_API_KEY = "AIzaSyCbG_fT2IbSNOEcHXUo9MYY_6hvZKIQ17E"

  SITE_URL = "https://toiture.conecto.ca"
  SITE_LANG_URL = "https://roofing.conecto.ca"
  BASE_LANGUAGE = "fr"
  SECOND_LANGUAGE = "en"
  BASE_SITE_TITLE = "Conecto Entrepreneur"
  CONTRACTOR_URL = "https://entrepreneur.conecto.ca"
